version: "3"
services:
    neo4j:
        image: neo4j:latest
        container_name: neo4j-db
        restart: unless-stopped
        ports:
            - 7474:7474
            - 7687:7687
        volumes:
            - ./neo4j/conf:/conf
            - ./neo4j/data:/data
            - ./neo4j/import:/import
            - ./neo4j/logs:/logs
            - ./neo4j/plugins:/plugins
            - ./neo4j/load:/load
        environment:
            - NEO4J_AUTH=neo4j/potassium
            - dbms.connector.bolt.listen_address=bolt://neo4j:pass@neo4j_db:7687
            - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
