name: dw_env
channels:
  - defaults
dependencies:
  - ca-certificates=2021.10.26
  - certifi=2021.10.8
  - openssl=1.1.1l
  - pip=21.2.4
  - python=3.9.7
  - requests=2.26.0
  - setuptools=58.0.4
  - sqlite=3.36.0
  - tk=8.6.11
  - tzdata=2021e
  - wheel=0.37.0
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - beautifulsoup4==4.10.0
    - redis==3.5.3
    - soupsieve==2.2.1